### ISSUE TITLE
the difference between model and model_cls

### ISSUE THREAD

**Issue by xiujiesong** [shawroad/Semantic-Textual-Similarity-Pytorch#7]
Hi,

What is the difference between model and model_cls in sentence-bert?

**Comment by shawroad** [comment]
model_cls采用的是分类损失。  model采用的是回归损失。  模型上的区别就是model_cls加了几层fc进行分类。model是将两个句子表示计算cos，然后回归。

**Comment by xiujiesong** [comment]
btw, this line is duplicated right?

https://github.com/shawroad/Semantic-Textual-Similarity-Pytorch/blob/4a031c551f6155577aa6c1ea7f238beaadc06e92/SentenceBert/run_sentencebert_cls.py#L114

**Comment by shawroad** [comment]
嗯嗯   谢谢  已删除

**Comment by xiujiesong** [comment]
thx!
